chopstick <- read.table("http://www.stat.ufl.edu/~winner/data/chopstick2_rcb.dat", header = F, col.names = c("efficiency", "treatment", "block"))
attach(chopstick)
treatment <- factor(treatment)
block <- factor(block)
chopstick.aov <- aov(efficiency ~ treatment + block)
summary(chopstick.aov)
qf(.95, 5, 150)
TukeyHSD(chopstick.aov,"treatment")
(a_mean <- as.vector(tapply(efficiency,treatment,mean)))
a_lev <- length(a_mean)
ssquared <- 2 * 4.23 / 31
Bon_MSD_A <- qt(1-(0.025/(a_lev*(a_lev-1)/2)),150)*sqrt(ssquared)
for(i1 in 1:(a_lev-1)) { 
for(i2 in (i1+1):a_lev) {
print(cbind(i1,i2,(a_mean[i1]-a_mean[i2])-Bon_MSD_A,(a_mean[i1]-a_mean[i2])+Bon_MSD_A))
}}
(mu_hat <- mean(efficiency))
(methodmean <- as.vector(tapply(efficiency,treatment,mean)))
(blockmean <- as.vector(tapply(efficiency,block,mean)))
(r <- length(methodmean))
(nb <- length(blockmean))
(tau_hat <- methodmean-mu_hat)
(rho_hat <- blockmean-mu_hat)
(tau_hat_y <- rep(tau_hat,nb))
(rho_hat_y <- rep(rho_hat,each=r))
(SSTO <- sum((efficiency-mean(efficiency))^2))
(SSTR <- sum(tau_hat_y^2))
(SSBL <- sum(rho_hat_y^2))
(SSBL.TR <- SSTO-SSTR-SSBL)
(SSBL.TR_Tukey <- ((sum(tau_hat_y*rho_hat_y*efficiency))^2)/
           ((sum(tau_hat^2))*(sum(rho_hat^2))))
(SSRem <- SSBL.TR-SSBL.TR_Tukey)
(F_BL.TR_Tukey <- (SSBL.TR_Tukey/1)/(SSRem/((r-1)*(nb-1)-1)))
(F_05 <- qf(0.95,1,(r-1)*(nb-1)-1))
(P_F_BL.TR <- 1-pf(F_BL.TR_Tukey,1,(r-1)*(nb-1)-1))
MSBL <- SSBL/(nb-1)
MSBL.TR <- SSBL.TR/((nb-1)*(r-1))
(eff_RBD <- ((nb-1)*MSBL + nb*(r-1)*MSBL.TR) /((nb*r-1)*MSBL.TR))
yhat <- predict(chopstick.aov)
e <- residuals(chopstick.aov)
plot(yhat,e,xlab="Yhat",ylab="Residual",main="Residuals versus Yhat")
qqnorm(e); qqline(e)
coffee <- read.table("http://www.stat.ufl.edu/~winner/data/shelfspace.dat", header = F, col.names = c("category", "store", "week", "space", "sales"))
attach(coffee)
category <- factor(category)
week <- factor(week)
space <- factor(space)
store <- factor(store)
newdata <- subset(coffee, category == 4)
attach(newdata)
coffee.aov1 <- aov(sales ~ store + week + space)
summary(coffee.aov1)
qf(.95, 5, 20)
TukeyHSD(coffee.aov1, "space")
(a_mean <- as.vector(tapply(sales,space,mean)))
a_lev <- length(a_mean)
ssquared <- 2 * 63.9 / 6
Bon_MSD_A <- qt(1-(0.025/(a_lev*(a_lev-1)/2)),(a_lev - 1)*(a_lev - 2))*sqrt(ssquared)
for(i1 in 1:(a_lev-1)) { 
for(i2 in (i1+1):a_lev) {
print(cbind(i1,i2,(a_mean[i1]-a_mean[i2])-Bon_MSD_A,(a_mean[i1]-a_mean[i2])+Bon_MSD_A))
}}
e <- (105.9 + 1295.2 + 5*63.9) / (7*63.9)
e
