denim <- read.table("http://www.stat.ufl.edu/~winner/data/denim_abrasion.dat", header = F, col.names = c("cycles", "treatment", "score"))
attach(denim)
cycles <- factor(cycles)
treatment <- factor(treatment)
(cell_mean <- as.vector(tapply(score,list(cycles,treatment),mean)))
(a_mean <- as.vector(tapply(score,cycles,mean)))
a_lev <- length(a_mean)
(b_mean <- as.vector(tapply(score,treatment,mean)))
b_lev <- length(b_mean)
ab_lev <- a_lev*b_lev
trt_ab <- rep(1:ab_lev,each=10)
trt_ab <- factor(trt_ab)
(all_mean <- mean(score))
denim.aov <- aov(score ~ cycles + treatment + cycles:treatment)
summary(denim.aov)
qf(.95, 4, 81)
qf(.95, 2, 81)
interaction.plot(cycles,treatment,score, ylim=c(0.7*min(score),1.3*max(score)))
interaction.plot(treatment,cycles,score, ylim=c(0.7*min(score),1.3*max(score)))
e <- residuals(denim.aov)
yhat <- predict(denim.aov)
sse <- deviance(denim.aov)
df.e <- df.residual(denim.aov)
mse <- sse/df.e
TukeyHSD(denim.aov,"cycles")
TukeyHSD(denim.aov,"treatment")
Bon_MSD_A <- qt(1-(0.025/(a_lev*(a_lev-1)/2)),df.e)*sqrt(2*mse/(b_lev*10))
Bon_MSD_B <- qt(1-(0.025/(b_lev*(b_lev-1)/2)),df.e)*sqrt(2*mse/(a_lev*10))
for(i1 in 1:(a_lev-1)) { 
for(i2 in (i1+1):a_lev) {
print(cbind(i1,i2,(a_mean[i1]-a_mean[i2])-Bon_MSD_A,(a_mean[i1]-a_mean[i2])+Bon_MSD_A))
}}
for(i1 in 1:(b_lev-1)) { 
for(i2 in (i1+1):b_lev) {
print(cbind(i1,i2,(b_mean[i1]-b_mean[i2])-Bon_MSD_B,(b_mean[i1]-b_mean[i2])+Bon_MSD_B))
}}
(cell_var <- as.vector(tapply(score,list(cycles,treatment),var)))
plot(yhat,e,xlab="Yht",ylab="Residual")
qqline(0)
fish <- read.table("C:\\Users\\Beans\\Desktop\\BRIDGE MAN\\Junior Year\\Spring Semester\\Design of Experiments\\fish.dat", header = F, col.names = c("year", "location", "catch", "logcatch"))
attach(fish)
year <- factor(year)
location <- factor(location)
fish.aov <- aov(logcatch ~ year + location)
summary(fish.aov)
qf(.95, 5, 15)
qf(.95, 3, 15)
(mu_hat <- mean(logcatch))
(yearmean <- as.vector(tapply(logcatch,year,mean)))
(locationmean <- as.vector(tapply(logcatch,location,mean)))
(a <- length(yearmean))
(b <- length(locationmean))
(alpha_hat <- yearmean-mu_hat)
(beta_hat <- locationmean-mu_hat)
(alpha_hat_y <- rep(alpha_hat,each=b))
(beta_hat_y <- rep(beta_hat,a))
(SSTO <- sum((logcatch-mean(logcatch))^2))
(SSA <- sum(alpha_hat_y^2))
(SSB <- sum(beta_hat_y^2))
(SSAB <- SSTO-SSA-SSB)
(SSAB_Tukey <- ((sum(alpha_hat_y*beta_hat_y*logcatch))^2)/
           ((sum(alpha_hat^2))*(sum(beta_hat^2))))
(SSRem <- SSAB-SSAB_Tukey)
(F_AB_Tukey <- (SSAB_Tukey/1)/(SSRem/((a-1)*(b-1)-1)))
(F_05 <- qf(0.95,1,(a-1)*(b-1)-1))
(P_F_AB <- 1-pf(F_AB_Tukey,1,(a-1)*(b-1)-1))
karate <- read.table("http://www.stat.ufl.edu/~winner/sta4211/karate_board1.dat",
           header=T)
attach(karate)
names(karate)
kb.mod1 <- lm(Y ~ X1 + X2 + X3 + X4 + X1X4 + X2X4 + X3X4)
anova(kb.mod1)
kb.mod2 <- lm(Y ~ X1 + X2 + X3 + X4)
anova(kb.mod2)
kb.mod3 <- lm(Y ~  X4 + X1X4 + X2X4 + X3X4)
anova(kb.mod3)
kb.mod4 <- lm(Y ~ X1 + X2 + X3 + X1X4 + X2X4 + X3X4)
anova(kb.mod4)
anova(kb.mod2,kb.mod1)
anova(kb.mod3,kb.mod1)
anova(kb.mod4,kb.mod1)
kb.mod5 <- aov(Y ~ factor(Wood))
anova(kb.mod5)
drop1(kb.mod5)
TukeyHSD(kb.mod5)

